version: "3"
services:
  # for development purposes
  tests: &tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_TENANT_ID
      - TEST_CLIENT_ID
      - TEST_CLIENT_SECRET
      - TEST_KEY_VAULT_URL
      - TEST_AWS_REGION
      - TEST_AWS_ACCESS_KEY_ID
      - TEST_AWS_SECRET_ACCESS_KEY
      - TEST_AWS_KMS_KEY_ID
      - TEST_AWS_ROLE_ID
      - TEST_GOOGLE_APPLICATION_CREDENTIAL
      - TEST_GCP_KMS_KEY_ID
    command: ["composer", "ci"]

  dev:
    <<: *tests
    volumes:
      - .:/code

  ci:
    <<: *tests
    build:
      context: .
      dockerfile: Dockerfile
    command: ["composer", "ci"]
    volumes:
      - ./build/logs/:/code/build/logs/
